import { Document, Types } from 'mongoose';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { MESSAGE_TYPE } from '../types/chat.types';

/**
 * Chat Message Document Type
 * Extends Mongoose Document with ChatMessage properties
 */
export type ChatMessageDocument = ChatMessage & Document;

/**
 * Chat Message Schema
 *
 * Represents a message in a chat room.
 *
 * Key Features:
 * - Links to chat room and sender
 * - Supports text messages (extensible for future message types)
 * - Tracks read status via readBy array
 * - Soft delete support via isDeleted flag
 *
 * Usage Example:
 * ```typescript
 * const message = await chatMessageModel.create({
 *   roomId: roomId,
 *   senderId: userId,
 *   content: 'Hello!',
 *   messageType: MESSAGE_TYPE.TEXT,
 * });
 * ```
 */
@Schema({
  timestamps: true,
  toJSON: {
    virtuals: true,
  },
})
export class ChatMessage {
  /**
   * Reference to the chat room this message belongs to
   * Required field
   */
  @Prop({ required: true, type: Types.ObjectId, ref: 'ChatRoom' })
  roomId: Types.ObjectId;

  /**
   * Reference to the user who sent this message
   * Required field
   */
  @Prop({ required: true, type: Types.ObjectId, ref: 'User' })
  senderId: Types.ObjectId;

  /**
   * Message content/text
   * Required field
   */
  @Prop({ required: true, type: String, trim: true })
  content: string;

  /**
   * Type of message
   * Currently only supports 'text', but can be extended
   * Default: 'text'
   */
  @Prop({
    required: true,
    type: String,
    enum: Object.values(MESSAGE_TYPE),
    default: MESSAGE_TYPE.TEXT,
  })
  messageType: MESSAGE_TYPE;

  /**
   * Array of user IDs who have read this message
   * Used to track read receipts
   * Empty array means message is unread by all participants
   */
  @Prop({
    type: [{ type: Types.ObjectId, ref: 'User' }],
    default: [],
  })
  readBy: Types.ObjectId[];

  /**
   * Soft delete flag
   * When true, message is considered deleted but data is preserved
   * Default: false
   */
  @Prop({ required: false, default: false, type: Boolean })
  isDeleted: boolean;

  /**
   * Auto-generated by Mongoose
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Auto-generated by Mongoose
   * Last update timestamp
   */
  updatedAt: Date;
}

/**
 * Create the Mongoose schema from the ChatMessage class
 */
export const ChatMessageSchema = SchemaFactory.createForClass(ChatMessage);

/**
 * Create indexes for efficient querying
 *
 * Indexes:
 * - roomId: For querying all messages in a room
 * - senderId: For querying all messages by a user
 * - createdAt: For sorting messages chronologically
 * - Compound index on (roomId, createdAt): For efficient pagination
 */
ChatMessageSchema.index({ roomId: 1, createdAt: -1 });
ChatMessageSchema.index({ senderId: 1 });
ChatMessageSchema.index({ createdAt: -1 });
