import { Document, Types } from 'mongoose';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

/**
 * Chat Unread Count Document Type
 * Extends Mongoose Document with ChatUnreadCount properties
 */
export type ChatUnreadCountDocument = ChatUnreadCount & Document;

/**
 * Chat Unread Count Schema
 *
 * Maintains unread message count per user per room for efficient counting.
 * Instead of counting messages on-the-fly, this schema maintains a counter
 * that is incremented/decremented as messages are sent/read.
 *
 * Key Features:
 * - Compound unique index on (roomId, userId) ensures one record per user per room
 * - Count is maintained atomically using MongoDB $inc operator
 * - Auto-initialized when first message is sent
 * - Count never goes below 0
 *
 * Usage Example:
 * ```typescript
 * // Get unread count
 * const unreadCount = await chatUnreadCountModel.findOne({
 *   roomId: roomId,
 *   userId: userId
 * });
 * const count = unreadCount?.count || 0;
 *
 * // Increment count
 * await chatUnreadCountModel.findOneAndUpdate(
 *   { roomId, userId },
 *   { $inc: { count: 1 } },
 *   { upsert: true, new: true }
 * );
 * ```
 */
@Schema({
  timestamps: true,
  toJSON: {
    virtuals: true,
  },
})
export class ChatUnreadCount {
  /**
   * Reference to the chat room
   * Required field
   */
  @Prop({ required: true, type: Types.ObjectId, ref: 'ChatRoom' })
  roomId: Types.ObjectId;

  /**
   * Reference to the user
   * Required field
   */
  @Prop({ required: true, type: Types.ObjectId, ref: 'User' })
  userId: Types.ObjectId;

  /**
   * Unread message count for this user in this room
   * Default: 0
   * Minimum: 0 (never negative)
   */
  @Prop({
    required: true,
    type: Number,
    default: 0,
    min: 0,
  })
  count: number;

  /**
   * Auto-generated by Mongoose
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Auto-generated by Mongoose
   * Last update timestamp
   */
  updatedAt: Date;
}

/**
 * Create the Mongoose schema from the ChatUnreadCount class
 */
export const ChatUnreadCountSchema =
  SchemaFactory.createForClass(ChatUnreadCount);

/**
 * Compound unique index on (roomId, userId)
 * Ensures only one unread count record exists per user per room
 *
 * Example: If record exists with roomId: "room1", userId: "user1",
 * another record with same combination cannot be created
 */
ChatUnreadCountSchema.index({ roomId: 1, userId: 1 }, { unique: true });

/**
 * Index on roomId for efficient queries by room
 * Useful for getting all unread counts for a room
 */
ChatUnreadCountSchema.index({ roomId: 1 });

/**
 * Index on userId for efficient queries by user
 * Useful for getting all unread counts for a user across all rooms
 */
ChatUnreadCountSchema.index({ userId: 1 });
