export enum CONFIG {
  TEMPLATES_PATH = 'TEMPLATES_PATH',

  EMAIL_SENDER = 'EMAIL_SENDER',
  EMAIL_CLIENT_API_KEY = 'EMAIL_CLIENT_API_KEY',

  SENDGRID_SENDER = 'SENDGRID_SENDER',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  EMAIL_PROVIDER = 'EMAIL_PROVIDER',

  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_REGION = 'AWS_REGION',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',
  AWS_EXPIRES_IN = 'AWS_EXPIRES_IN',
}
