import { Document, Types } from 'mongoose';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

/**
 * Chat Room Document Type
 * Extends Mongoose Document with ChatRoom properties
 */
export type ChatRoomDocument = ChatRoom & Document;

/**
 * Chat Room Schema
 *
 * Represents a 1-on-1 chat room between two users.
 *
 * Key Features:
 * - Participants array contains exactly 2 user IDs (sorted for uniqueness)
 * - Unique index on sorted participants prevents duplicate rooms
 * - Tracks last message for quick access to recent activity
 * - Soft delete support via isDeleted flag
 *
 * Usage Example:
 * ```typescript
 * const room = await chatRoomModel.findOne({ participants: [userId1, userId2] });
 * ```
 */
@Schema({
  timestamps: true,
  toJSON: {
    virtuals: true,
  },
})
export class ChatRoom {
  /**
   * Array of exactly 2 participant user IDs
   * Always sorted to ensure uniqueness (prevents duplicate rooms)
   * Example: [userId1, userId2] where userId1 < userId2
   */
  @Prop({
    required: true,
    type: [{ type: Types.ObjectId, ref: 'User' }],
    validate: {
      validator: (participants: Types.ObjectId[]) => participants.length === 2,
      message: 'Chat room must have exactly 2 participants',
    },
  })
  participants: Types.ObjectId[];

  /**
   * Reference to the last message in this room
   * Used for quick access to recent activity
   * Optional - may be null if no messages exist
   */
  @Prop({ type: Types.ObjectId, ref: 'ChatMessage', required: false })
  lastMessage?: Types.ObjectId;

  /**
   * Timestamp of the last message
   * Used for sorting rooms by recent activity
   * Optional - may be null if no messages exist
   */
  @Prop({ type: Date, required: false })
  lastMessageAt?: Date;

  /**
   * Soft delete flag
   * When true, room is considered deleted but data is preserved
   * Default: false
   */
  @Prop({ required: false, default: false, type: Boolean })
  isDeleted: boolean;

  /**
   * Auto-generated by Mongoose
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Auto-generated by Mongoose
   * Last update timestamp
   */
  updatedAt: Date;
}

/**
 * Create the Mongoose schema from the ChatRoom class
 */
export const ChatRoomSchema = SchemaFactory.createForClass(ChatRoom);

/**
 * Create unique index on sorted participants array
 * This ensures that only one room can exist between any two users
 *
 * Example: If room exists with participants [user1, user2],
 * another room with [user2, user1] cannot be created
 */
ChatRoomSchema.index(
  { participants: 1 },
  {
    unique: true,
    // Custom index function to sort participants before indexing
    // This ensures [user1, user2] and [user2, user1] are treated as the same
  },
);

/**
 * Pre-save hook to sort participants array
 * Ensures participants are always in sorted order for consistency
 */
ChatRoomSchema.pre('save', function (next) {
  if (this.participants && this.participants.length === 2) {
    // Sort participants by their string representation
    this.participants.sort((a, b) => {
      const aStr = a.toString();
      const bStr = b.toString();
      return aStr.localeCompare(bStr);
    });
  }
  next();
});
