export enum CONFIG {
  PORT = 'PORT',
  MONGODB_URI = 'MONGODB_URI',
  EXTERNAL_MONGODB_URI = 'EXTERNAL_MONGODB_URI',
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET = 'AWS_S3_BUCKET',
  AWS_CLOUDFRONT_DOMAIN = 'AWS_CLOUDFRONT_DOMAIN',
}
