export const RESPONSE = {
  AUTH: {
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logged out successfully',
    TOKEN_REFRESHED: 'Token refreshed',
    INVITE_VALID: 'Invitation is valid',
    REGISTER_SUCCESS: 'Registration successful',
    INVITE_ACCEPTED: 'Invitation accepted successfully',
    INVALID_CREDENTIALS: 'Invalid credentials',
    INVALID_TOKEN: 'Invalid or expired token',
  },
  USERS: {
    INVITED: 'Invitation sent successfully',
    FETCHED: 'Users fetched successfully',
    UPDATED: 'User updated successfully',
    DELETED: 'User deleted successfully',
    RESTORED: 'User restored successfully',
    EXPORTED: 'User data exported successfully',
  },
  DEPARTMENTS: {
    CREATED: 'Department created successfully',
    FETCHED: 'Departments fetched successfully',
    UPDATED: 'Department updated successfully',
    DELETED: 'Department deleted successfully',
  },
  CLINIC_SETTINGS: {
    FETCHED: 'Clinic settings fetched',
    UPDATED: 'Clinic settings updated',
    SLOT_BLOCKED: 'Time slot blocked',
    SLOT_UNBLOCKED: 'Time slot unblocked',
  },
  SERVICES: {
    CREATED: 'Service created successfully',
    FETCHED: 'Services fetched successfully',
    UPDATED: 'Service updated successfully',
    DELETED: 'Service deleted successfully',
  },
  APPOINTMENTS: {
    CREATED: 'Appointment created successfully',
    FETCHED: 'Appointments fetched successfully',
    UPDATED: 'Appointment updated successfully',
    PATIENT_UPDATED: 'Patient updated successfully',
    CANCELLED: 'Appointment cancelled successfully',
    RESCHEDULED: 'Appointment rescheduled successfully',
    RECONFIRMED: 'Appointment reconfirmed successfully',
    STATUS_UPDATED: 'Appointment status updated',
    CONFIRMATION_SMS_SENT: 'Appointment confirmation SMS sent',
    STATS_FETCHED: 'Appointment stats fetched',
    HISTORY_FETCHED: 'Appointment history fetched',
    PATIENT_HISTORY_FETCHED: 'Patient history fetched',
  },
  BOOKING: {
    CREATED: 'Booking created successfully',
    SERVICES_FETCHED: 'Services fetched',
    SLOTS_FETCHED: 'Available time slots fetched',
    INFO_FETCHED: 'Booking info fetched',
    SLOT_UNAVAILABLE: 'Selected time slot is no longer available',
    CLINIC_NOT_FOUND: 'Clinic not found',
  },
  INTAKE: {
    INFO_FETCHED: 'Booking info fetched',
    SUBMITTED: 'Intake form submitted successfully',
    FORM_FETCHED: 'Intake form fetched',
  },
};
